### ISSUE TITLE
Can't disable default "Super" action

### ISSUE THREAD

**Issue by cjshearer** [tristanbeedell/hm-cosmic#1]
Unless I'm missing something, it looks like this API won't provide a way to disable the default action of opening the launcher with the "Super" key, while also having other binds that base off of "Super".

```nix
{ pkgs, config, lib, ... }:
let inherit (config.lib.cosmic) Actions mapBinds;
in lib.mkIf config.programs.cosmic.enable {
  programs.cosmic.input.binds = mapBinds {
      Super."slash" = Actions.Disable; # attribute 'Super' already defined
      Super = Actions.Disable;
    };
  };
}
```

Maybe we need something like this?

```nix
{ pkgs, config, lib, ... }:
let inherit (config.lib.cosmic) Actions mapBinds;
in lib.mkIf config.programs.cosmic.enable {
  programs.cosmic.input.binds = mapBinds [
      { Super."slash" = Actions.Disable; }
      { Super = Actions.Disable; }
    ];
  };
}
```

Or perhaps this?

```nix
{ pkgs, config, lib, ... }:
let inherit (config.lib.cosmic) Actions mapBinds;
in lib.mkIf config.programs.cosmic.enable {
  programs.cosmic.input.binds = mapBinds {
      Super."slash" = Actions.Disable;
      Super.self;
    };
  };
}
```

**Comment by tristanbeedell** [comment]
aha, it seems I haven't built in support for not defining a key. That needs fixing.

Note, the mapBinds func actually casts the attrset into a list, which is then accepted by the module.

It is already possible to add actions as follows:

```nix
mapBinds {
 Super."slash" = Actions.Disable;
}
++ [{modifiers = ["Super"]; key = "d"; action = "Disable";}];
```

Setting the Super key behavior in cosmic-settings produces this shortcut:

```
(
    modifiers: [
        Super,
    ],
): System(Launcher),
```

So it would be worth allowing the key to be set to null for this, i.e.:

```nix
{modifiers = ["Super"]; action = "System"; value = "Launcher";}
```

I like the idea of adding an action / self property to the hotkeys in the tree:

```nix
mapBinds {
 Super.action = Actions.Disable;
 Super."slash" = Actions.Disable;
}
```

**Comment by tristanbeedell** [comment]
fixed and updated the example:
https://github.com/tristanbeedell/hm-cosmic/blob/8c7ae2855827101eff7e52dd320599a487c78936/example.nix#L39
